import time
import os

# Una historia de amor

os.system('cls')
print(" Hay un policia ")
print("                      * ")
print("                      * ")
print("                      * ")
print("                      * ")
print("                      * ")

time.sleep(2)
os.system('cls')
print(" Tres palomas ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")

time.sleep(2)
os.system('cls')
print(" Una iglesia ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               * ")
print("             *   * ")
print("            *     * ")
print("           *       * ")
print("          *         * ")

time.sleep(2)
os.system('cls')
print(" Dos amigos ")
#Amigo 1
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               *            * ")
print("             *   *         * ")
print("            *     *       * ")
print("           *       *     * ")
print("          *         *   * ")
time.sleep(1)
os.system('cls')
print(" Dos amigos ")
#Amigo 2
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     * ")
print("             *   *         *       * ")
print("            *     *       *         * ")
print("           *       *     *           * ")
print("          *         *   *             * ")

time.sleep(2)
os.system('cls')
print(" Y media luna ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            *     *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")

time.sleep(2)
os.system('cls')
print(" El policía dispara ")
#Disparo 1
print("                * *   *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            *     *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")
time.sleep(1)
os.system('cls')
print(" El policía dispara ")
#Disparo 2
print("                * * * * *        * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            *     *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")
time.sleep(1)
os.system('cls')
print(" El policía dispara ")
#Disparo 3
print("                * * * * * * *    * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            *     *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")

time.sleep(2)
os.system('cls')
print(" Las palomas vuelan ")
#vuela 1
print("                * * * * * * *    * * * * * ")
print("                      * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            *     *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")
time.sleep(1)
os.system('cls')
print(" Las palomas vuelan ")
#vuela 2
print("                * * * * * * *    * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            *     *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")

time.sleep(2)
os.system('cls')
print(" La iglesia cierra ")
#cierra 1
print("                * * * * * * *    * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            * *   *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")
time.sleep(1)
os.system('cls')
print(" La iglesia cierra ")
#cierra 2
print("                * * * * * * *    * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         *       *       * ")
print("            * * * *       *         *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")

time.sleep(2)
os.system('cls')
print(" Los amigos se juntan ")
#juntan 1
print("                * * * * * * *    * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         * *     *       * ")
print("            * * * *       *   *     *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")
time.sleep(1)
os.system('cls')
print(" Los amigos se juntan ")
#juntan 2
print("                * * * * * * *    * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * ")
print("             *   *         * *   * *       * ")
print("            * * * *       *   * *   *      * ")
print("           *       *     *           *     * ")
print("          *         *   *             *     * * ")

time.sleep(2)
os.system('cls')
print(" La luna se llena ")
print("                * * * * * * *    * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print("                      *          * ")
print("                      *          * * * * * ")
print(" ")
print("               *            *     *         * * * ")
print("             *   *         * *   * *       *     * ")
print("            * * * *       *   * *   *      *     * ")
print("           *       *     *           *     *     * ")
print("          *         *   *             *     * * * ")
print(" ")
time.sleep(2)
os.system('cls')
print(" La amiga se escapa ")
#escapa 1
print("                                         * * * * ")
print("                                       *          * ")
print("                                     *              * ")
print("                                   *                  * ")
print("                                 *                      * ")
print("                                *                        * ")
print("                                                          * ")
print("                * * * * * * *    * * * * *                 * ")
print("                      *          *                         * ")
print("                      *          * * * * *                 * ")
print("                      *          *                         * ")
print("                      *          * * * * *                 * ")
print("                                                           * ")
print("               *            *     *         * * *          * ")
print("             *   *         * *   * *       *     *         * ")
print("            * * * *       *   * *   *      *     *         * ")
print("           *       *     *           *     *     * ")
print("          *         *   *             *     * * * ")
time.sleep(1)
os.system('cls')
print(" La amiga se escapa ")
#escapa 2
print("                                         * * * * ")
print("                                       *          * ")
print("                                     *              * ")
print("                                   *                  * ")
print("                                 *                      * ")
print("                                *                        * ")
print("                                                          * ")
print("                * * * * * * *    * * * * *                 * ")
print("                      *          *                         * ")
print("                      *          * * * * *                 * ")
print("                      *          *                         * ")
print("                      *          * * * * *                 * ")
print("                                                           * ")
print("               *            *     *         * * *          * ")
print("             *   *         * *   * *       *     *         * ")
print("            * * * *       *   * *   *      *     *         * ")
print("           *       *     *           *     *     *         * ")
print("          *         *   *             *     * * *         * ")
print("                                                         * ")
print("                                                        * ")
print("                                                      * ")
print("                                                    * ")
print("                                                  * ")
print("                                                * ")
print("                                              * ")
print("                                            * ")
print("                                          * ")
print("                                        * ")
print("                                      * ")
print("                                    * ")
print("                                  * ")
print("                                * ")
print("                               * ")

time.sleep(2)
os.system('cls')
print(" El amigo la atrapa ")
#atrapa 1
print("              * * * *                    * * * * ")
print("            *          *               *          * ")
print("         *               *           *              * ")
print("       *                   *       *                  * ")
print("     *                       *   *                      * ")
print("    *                         * *                        * ")
print("   *                                                      * ")
print("  *             * * * * * * *    * * * * *                 * ")
print("  *                   *          *                         * ")
print("  *                   *          * * * * *                 * ")
print("  *                   *          *                         * ")
print("  *                   *          * * * * *                 * ")
print("  *                                                        * ")
print("  *            *            *     *         * * *          * ")
print("  *          *   *         * *   * *       *     *         * ")
print("  *         * * * *       *   * *   *      *     *         * ")
print("  *        *       *     *           *     *     *         * ")
print("          *         *   *             *     * * *         * ")
print("                                                         * ")
print("                                                        * ")
print("                                                      * ")
print("                                                    * ")
print("                                                  * ")
print("                                                * ")
print("                                              * ")
print("                                            * ")
print("                                          * ")
print("                                        * ")
print("                                      * ")
print("                                    * ")
print("                                  * ")
print("                                * ")
print("                               * ")
time.sleep(1)
os.system('cls')
print(" El amigo la atrapa ")
#atrapa 2
print("             * * * *                    * * * *  ")
print("           *          *               *          * ")
print("        *               *           *              * ")
print("      *                   *       *                  * ")
print("    *                       *   *                      * ")
print("   *                         * *                        * ")
print("  *                                                      * ")
print(" *             * * * * * * *    * * * * *                 * ")
print(" *                   *          *                         * ")
print(" *                   *          * * * * *                 * ")
print(" *                   *          *                         * ")
print(" *                   *          * * * * *                 * ")
print(" *                                                        * ")
print(" *            *            *     *         * * *          * ")
print(" *          *   *         * *   * *       *     *         * ")
print(" *         * * * *       *   * *   *      *     *         * ")
print(" *        *       *     *           *     *     *         * ")
print("  *      *         *   *             *     * * *         * ")
print("   *                                                    * ")
print("    *                                                  * ")
print("      *                                              *  ")
print("        *                                          * ")
print("          *                                      * ")
print("            *                                  * ")
print("              *                              * ")
print("                *                          * ")
print("                  *                      * ")
print("                    *                  * ")
print("                      *              * ")
print("                        *          * ")
print("                          *      * ")
print("                            *  * ")
print("                             ** ")